CREATE TABLE IF NOT EXISTS bbs_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    body TEXT NOT NULL,
    image_filename VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
